name: caesar_cipher
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  salomon_bottom_bar: ^3.3.1
  flutter_native_splash: ^2.2.12
  clipboard: ^0.1.3
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.10.0"
  change_app_package_name: ^1.1.0

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/images/logo.png"
   min_sdk_android: 16 # android min sdk min:16, default 21

flutter_native_splash:

  color: "#003A70"
  image: assets/images/logo.png
  branding: assets/images/logo.png
  branding_mode: center


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900

